QUESTIONAIR_DICT = {'01': 'Dribbling of saliva during the daytime',
 '02': 'Loss or change in your ability to taste or smell',
 '03': 'Difficulty swallowing food or drink or problems with choking',
 '04': 'Vomiting or feelings of sickness (nausea)',
 '05': 'Constipation (less than 3 bowel movements a week) or having to strain to pass a stool (faeces)',
 '06': 'Bowel (fecal) incontinence',
 '07': 'Feeling that your bowel emptying is incomplete after having been to the toilet',
 '08': 'A sense of urgency to pass urine makes you rush to the toilet',
 '09': 'Getting up regularly at night to pass urine',
 '10': 'Unexplained pains (not due to known conditions such as arthritis)',
 '11': 'Unexplained change in weight (not due to change in diet)',
 '12': 'Problems remembering things that have happened recently or forgetting to do things',
 '13': 'Loss of interest in what is happening around you or doing things',
 '14': 'Seeing or hearing things that you know or are told are not there',
 '15': 'Difficulty concentrating or staying focussed',
 '16': 'Feeling sad, low or blue',
 '17': 'Feeling anxious, frightened or panicky',
 '18': 'Feeling less interested in sex or more interested in sex',
 '19': 'Finding it difficult to have sex when you try',
 '20': 'Feeling light headed, dizzy or weak standing from sitting or lying',
 '21': 'Falling',
 '22': 'Finding it difficult to stay awake during activities such as working, driving or eating',
 '23': 'Difficulty getting to sleep at night or staying asleep at night',
 '24': 'Intense, vivid dreams or frightening dreams',
 '25': 'Talking or moving about in your sleep as if you are acting out a dream',
 '26': 'Unpleasant sensations in your legs at night or while resting, and a feeling that you need to move',
 '27': 'Swelling of your legs',
 '28': 'Excessive sweating',
 '29': 'Double vision',
 '30': 'Believing things are happening to you that other people say are not true'}
